name: scoped_model_demo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'
###########################################################################
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  scoped_model: ^2.0.0
  get_it: ^7.7.0
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  equatable: ^2.0.5
  permission_handler: ^11.3.1
  intl: ^0.19.0
  http: ^1.2.2
  dio: ^5.4.0
  dartz: ^0.10.1
  easy_localization: ^3.0.7
  cached_network_image: ^3.3.1
  freezed_annotation: ^2.0.0
  auto_route: ^8.3.0
  json_annotation: ^4.9.0
  image_picker: ^0.8.4+3
  persistent_bottom_nav_bar: ^6.2.1
  flutter_native_splash: ^2.4.1
  local_auth: ^2.2.0
  geolocator: ^12.0.0
  flutter_dialogs: ^3.0.0
  geocoding: ^3.0.0
  google_maps_flutter: ^2.9.0
  url_launcher: ^6.0.20
  carousel_slider: ^5.0.0
###########################################################################
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.0.0
  freezed: ^2.5.2
  auto_route_generator: ^8.1.0
  json_serializable: ^6.8.0

###########################################################################
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_light.png"

###########################################################################
flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image: "assets/images/splash_background_image.png"
  android_12:
    background_image: "assets/images/splash_background_image.png"
###########################################################################
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/translations/
#########